# need to add x and y position of robot to get moer accruavte things
string u  # first waypoint robot is in between
string v  # second waypoint robot is in between
int8 floor_number  # e.g. 1, 2
string target # label of the target waypoint e.g. "903-314"
---
bool success # indicate successful run of triggered service
string message # information e.g. for error messages
string[] waypoints  # lidy of waypoints robot will travel to
