geometry_msgs/Point location # x and y position
int8 floor_number  # e.g. 1, 2
string target # label of the target waypoint e.g. "903-314"
---
bool success # indicate successful run of triggered service
string message # information e.g. for error messages
WaypointNode[] waypoints  # lidy of waypoints robot will travel to
bool door_service_required
bool elevator_required
string[] doors_required
